config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions

    root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/sign_up',  to: 'users#new'
  match '/log_in',  to: 'sessions#new'
  match '/log_out', to: 'sessions#destroy'#, via: :delete

end

app/models/p_user.rb
class PUser < ParseResource::Base
  #attr_accessible :name, :email, :password, :password_confirmation
  #fields :name, :email
  field :name
  field :email
  field :password_digest

  before_save { |user| user.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  #
  #validates :password, presence: true, length: { minimum: 6 }
  #validates :password_confirmation, presence: true

  #validates :email, uniqueness: { case_sensitive: false }
  #validates :email, UniquenessValidator: true
  #validates_uniqueness_of :email
  #validates_presence_of :name

end

app/models/user.rb
# app/models/user.rb
class User < ParseUser

  # Note no " < ActiveRecord::Base"

  #attr_accessible :username, :name, :email, :password, :password_confirmation
  #attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :username, :name, :password, :password_confirmation
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username

  #  *** Does not seem to with with ParseUser ***
  #validates_uniqueness_of :email

  # you can add fields, like any other kind of Object...
  fields :name, :bio, :username

  # but note that email is a special field in the Parse API.
  fields :email, :remember_token

  # no validations included, but feel free to add your own
  #validates_presence_of :username

  before_save { |user| user.username = username.downcase }


  before_save :create_remember_token

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end



  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, format: { with: VALID_EMAIL_REGEX }


end


#class User < ParseResource::Base
#  field :name
#  field :email
#
#end


#class User < ActiveRecord::Base
#  attr_accessible :email, :name
#
#  validates :name, presence: true
#  #validates :email, UniquenessValidator: true
#
#end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  include SessionsHelper   # Hartl Authentication method

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if
      session[:user_id]
  end
end

app/controllers/kim_controller.rb
class KimController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #render"new"

    #*** Hartl Suggestion ***
  #user = User.find_by_username(params[:session][:username].downcase)
  #  if user && User.authenticate(params[:session][:username], params[:session][:password])
  #    sign_in user
  #    redirect_to user
  #  else
  #    flash.now[:error] = 'Invalid email/password combination' # Not quite right!
  #    render 'new'
  #  end

    #*** ParseResource Suggestion ***
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "You are signed in !"
    else
      flash.now[:error] = "Invalid username or password ...... create action"
      render "new"
    end
  end

  #
  #def directin
  #  user = User.authenticate(thisuser)
  #  if user
  #    session[:user_id] = user.id
  #    redirect_to root_url, :notice => "You are signed in !"
  #  else
  #    flash.now[:error] = "Invalid username or password ......directin action"
  #    render "new"
  #  end
  #end
  #
  #def signinnow
  #  thisuser[:username => "kimardenmiller@gmail.com", :password => "lockup99"]
  #  #@temp = params[username: "kimardenmiller@gmail.com"], params[password: "lockup99"]
  #  directin
  #end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out via the destroy method!"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    #@user = User.find(params[:user_id])
    @user = User.find_by_objectId(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      #redirect_to @user, :notice => "You are now Signed up! (Older)"
      #sign_in @user
      flash[:success] = "Welcome to Spokenvote! Please sign in"
      redirect_to @user
      #redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Spokenvote"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/kim_helper.rb
module KimHelper
end

app/helpers/sessions_helper.rb
# Hartl Authentication, which I dont' think works with Parse ***

module SessionsHelper

  #def sign_in(newuser)
  #  user = User.authenticate(newuser)
  #  if user
  #    session[:user_id] = user.id
  #    redirect_to root_url, :notice => "You are signed in !"
  #  else
  #    flash.now[:error] = "Invalid username or password ......SessionsHelper"
  #    render "new"
  #  end
  #end

  def sign_in(user)
    #cookies.permanent[:remember_token] = user.remember_token
    #cookies.permanent[:remember_token] = user.sessionToken
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
      @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_sessionToken(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.username.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://spokenvote.org/">Spokenvote</a>
    by Rails for Charity
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.spokenvote.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--<header class="navbar navbar-fixed-top">-->
<!--<div class="navbar-inner">-->
<!--<div class="container">-->
<!--<%= link_to "Spokenvote", '#', id: "logo" %>-->
<!--<nav>-->
<!--<ul class="nav pull-right">-->
<!--<li><%= link_to "Home",    root_path %></li>-->
<!--<li><%= link_to "Help",    help_path %></li>-->
<!--<% if current_user %>-->
    <!--<li>Logged in as <%= current_user.username %></li>-->
    <!--<li><%= link_to "Log out", log_out_path %></li>-->
    <!--<% else %>-->
    <!--<li><%= link_to "Sign up", sign_up_path %></li>-->
    <!--<li>or</li>-->
    <!--<li><%= link_to "Sign in", log_in_path %></li>-->
    <!--<% end %>-->
<!--</ul>-->
<!--</nav>-->
<!--</div>-->
<!--</div>-->
<!--</header>-->

<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
<div class="container">
<%= link_to "Spokenvote", root_path, id: "logo" %>
<nav>
<ul class="nav pull-right">
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>
<% if current_user %>
    <li>Logged in as <%= current_user.username %></li>
    <li><%= link_to "Users", '#' %></li>
    <li id="fat-menu" class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Account <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to "Settings", '#' %></li>
    <li class="divider"></li>
    <li>
    <%= link_to "Sign out", log_out_path, method: "delete" %>
    </li>
    </ul>
    </li>
    <% else %>
    <li><%= link_to "Sign in", log_in_path %></li>
    <% end %>
</ul>
</nav>
</div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<!--<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>-->
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>

<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>

      <!--<%= link_to "Test Link", sessions_path(username: "kimardenmiller@gmail.com", password: "lockup99"), method: "create", class: "btn btn-large btn-primary" %>-->

  <!--<%= link_to "Test 2", sessions_path(:method => "directin"), method: "directin", class: "btn btn-large btn-primary" %>-->




  <%= yield %>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About Us") %>
<html>
<body>
<h1>Spokenvote.org</h1>

<h2>Pure and Trusted Social Consensus</h2>
<p>
  Spokenvote.org is a Web-based social consensus tool for groups of any size, from a local school board to an entire nation’s people, that radically enhances the group’s ability to reach consensus via an intuitive democratic process. Deeply inspired by Wikipedia, Spokenvote is an open-source, non-profit “spark” project optimally timed to set off a forest fire of change.
  <br><br>
  Today’s transformative landscape in social media is rapidly mixing with a generation impatient to be heard and empowered and unwilling to endure the paralysis of today’s political system. Next, consider the growing momentum of open-source, crowd-sourcing, and crowd-funding, and you have a perfect storm at the center of which some trusted, open entity will very soon find itself. We don’t believe that entity will be the government, and are almost equally sure it won’t be Facebook or Google. We believe it will be Spokenvote.
  <br>    <br>
  The central idea behind Spokenvote is to spontaneously capture people’s opinions and ideas as they naturally come up and then harness the power of crowds to turn those diverse views, opinions, and revelations into clear statements of consensus connected to large groups. Such a pivotal step is made possible by helping users organically adjust their own semantics (the way they phrased a vote), and as they make those adjustments, progress toward reaching a majority opinion together.
  <br>        <br>
  Spokenvote delivers a high-value proposition through:
  <br><br>
  Radical openness that inspires trust and a sense of ownership, like that achieved by Wikipedia today
  <br><br>
  Technology and practices that intelligently, but unobtrusively, prompt and guide users into the most common semantic variation of their statement (much as Google guides one in phrasing a search string), allowing them to quickly “swarm” an issue to reach majority consensus together
  <br><br>
  A foundation of neutrality in which Spokenvote never curates or manipulates content, giving users a real and authentic sense of ownership

</p>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Spokenvote at
  <a href="http://spokenvote.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<html>
<body>
<h1>Spokenvote Help</h1>
<p>
  This is the help page for the
  <a href="http://spokenvote.org/">Spokenvote</a>
</p>
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title) %>
<!--<html>-->
    <!--<body>-->
    <!--<h1>Spokenvote Home</h1>-->
    <!--<p>-->
      <!--This is the home page for the-->
      <!--<a href="http://spokenvote.org/">Spokenvote</a>-->
      <!--Sample application.-->
    <!--</p>-->
    <!--</body>-->
<!--</html>-->

<div class="center hero-unit">
  <h1>Welcome to Spokenvote</h1>

  <h2>
    This is the sample page for
    <a href="http://spokenvote.org/">Spokenvote</a>.
  </h2>

  <%= link_to "Sign up now!", sign_up_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>

<div class="row">
  <div class="span6 offset3">

    <!--*** partialed out ***-->
    <!--<% if @user.errors.any? %>-->
        <!--<div class="error_messages">-->
          <!--<h2>Form is invalid</h2>-->
          <!--<ul>-->
            <!--<% for message in @user.errors.full_messages %>-->
                <!--<li><%= message %></li>-->
            <!--<% end %>-->
          <!--</ul>-->
        <!--</div>-->
    <!--<% end %>-->

    <%= form_for @user do |f| %>
        <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :username, "Username (Email Address)" %>
      <%= f.text_field :username %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

    <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
   <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>